// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Memo

package models

// MemoSlice is a slice of type Memo. Use it where you would use []Memo.
type MemoSlice []Memo

// Where returns a new MemoSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv MemoSlice) Where(fn func(Memo) bool) (result MemoSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}
